name: Kali/Debian RDP
on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest   # GitHub لا يوفر Runner Kali رسمي، Ubuntu يمكن استعماله كـ Debian base
    timeout-minutes: 3600
    steps:
      - name: Update system and install XFCE + XRDP
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies xfce4-session xfconf xrdp curl netcat-openbsd
          echo "startxfce4" > ~/.xsession
          chmod +x ~/.xsession
          sudo systemctl enable xrdp
          sudo systemctl restart xrdp

      - name: Create RDP User with Static Password
        run: |
          USERNAME="TOOLBOXKALI"
          PASSWORD="admin@123"
          if ! id -u $USERNAME >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash $USERNAME
            echo "$USERNAME:$PASSWORD" | sudo chpasswd
            sudo usermod -aG sudo $USERNAME
          fi
          echo "RDP_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID

      - name: Get Tailscale IP
        run: |
          TS_IP=$(tailscale ip -4)
          if [ -z "$TS_IP" ]; then
            echo "Tailscale IP not assigned. Exiting."
            exit 1
          fi
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Verify RDP Accessibility
        run: |
          TS_IP=$TAILSCALE_IP
          nc -zv $TS_IP 3389
          if [ $? -ne 0 ]; then
            echo "TCP connection to RDP port 3389 failed"
            exit 1
          fi
          echo "TCP connectivity successful!"

      - name: Maintain Connection
        run: |
          echo -e "\n=== RDP ACCESS ==="
          echo "Address: $TAILSCALE_IP"
          echo "Username: TOOLBOXKALI"
          echo "Password: admin@123"
          echo "==================\n"
          while true; do
            echo "[$(date)] RDP Active - Use Ctrl+C in workflow to terminate"
            sleep 300
          done
